import yaml
quarto_yml = '_quarto.yml'
with open(quarto_yml, 'r') as infile:
    quarto_meta = yaml.full_load(infile)

pdf_output = f"{quarto_meta['project']['output-dir']}/{quarto_meta['book']['output-file']}.pdf"

rule targets:
    input:
        pdf_output

rule update_extension:
    output:
        directory("_extensions/kelly-sovacool/rackham/")
    shell:
        """
        quarto update extension kelly-sovacool/rackham
        """

rule render_pdf:
    input:
        yml = quarto_yml,
        qmd = quarto_meta['book']['chapters'],
        bib = 'references.bib',
        ext = rules.update_extension.output
    output:
        pdf = pdf_output,
        tex = f"{quarto_meta['book']['output-file']}.tex"
    shell:
        """
        quarto render --to rackham-pdf
        """
