project:
  type: book
  output-dir: _book

book:
  title: |
    Improving machine learning models for microbiome analysis
    and democratizing data science along the way
  output-file: dissertation_KLS
  author:
    - name: Kelly L. Sovacool
      orcid: 0000-0003-3283-829X
      email: sovacool@umich.edu
  date: "2023-06-08"
  date-format: YYYY
  search: true
  repo-url: https://github.com/kelly-sovacool/phd-diss
  site-url: http://sovacool.dev/phd-diss/
  twitter-card: true
  downloads: [pdf]
  chapters:
    - index.qmd
    - chapters/optifit.qmd
    - chapters/cdiff.qmd
    - chapters/data-science.qmd
    - chapters/discussion.qmd

dept: Bioinformatics
#preface:
dedication: |
  TODO
acknowledgements: |
  TODO
abstract: |
  TODO
committee: # alphabetical order
  - Professor Patrick D. Schloss, Chair
  - Associate Professor Gregory J. Dick
  - Associate Professor Peter L. Freddolino
  - Associate Professor Jenna Wiens
  - Professor Vincent B. Young
chair: Professor Patrick D. Schloss, Chair
acronyms:
  \acro{OTU}{Operational Taxonomic Unit}
frontispiece: front-matter/frontispiece.png
list-commands:
  - \showlistoffigures
  #- \showlistoftables
  #- \showlistofappendices
  - \showlistofacronyms

bibliography: references.bib
fontsize: 12pt
format:
  rackham-pdf:
    keep-tex: true
    classoption:
      - thesis
    include-in-header: header.tex
    fig-cap-location: top

execute:
  freeze: auto
  cache: true
  eval: true
  echo: false
engine: knitr
