project:
  type: book
  output-dir: _book

book:
  title: |
    Improving machine learning models for microbiome analysis
    and democratizing data science along the way
  output-file: dissertation_KLS
  author:
    - name: Kelly L. Sovacool
      orcid: 0000-0003-3283-829X
      email: sovacool@umich.edu
  date: "2023-06-08"
  date-format: YYYY
  search: true
  repo-url: https://github.com/kelly-sovacool/phd-diss
  site-url: http://sovacool.dev/phd-diss/
  twitter-card: true
  downloads: [pdf]
  chapters:
    - index.qmd
    - chapters/optifit.qmd
    - chapters/cdiff.qmd
    - chapters/data-science.qmd
    - chapters/discussion.qmd

dept: Bioinformatics
frontispiece: front-matter/frontispiece.png
dedication: \input{front-matter/dedication.tex}
acknowledgements: \input{front-matter/acknowledgements.tex}
abstract: \input{front-matter/abstract.tex}
acronyms: \input{front-matter/acronyms.tex}
committee: # alphabetical order
  - Professor Patrick D. Schloss, Chair
  - Associate Professor Gregory J. Dick
  - Associate Professor Peter L. Freddolino
  - Associate Professor Jenna Wiens
  - Professor Vincent B. Young
chair: Professor Patrick D. Schloss, Chair
list-commands:
  - \showlistoffigures
  - \showlistoftables
  - \showlistofacronyms

bibliography: references.bib
format:
  rackham-pdf:
    keep-tex: true
    classoption:
      - thesis
    include-in-header: header.tex
    fig-cap-location: top

execute:
  freeze: auto
  cache: false
  eval: true
  echo: false
  message: false
  warning: false
engine: knitr
