project:
  type: book

book:
  title: | 
    Improving machine learning models for gut microbiome classification problems 
  subtitle: |
    and democratizing data science along the way
  output-file: dissertation_KLS
  author:
    - name: Kelly L. Sovacool
      orcid: 0000-0003-3283-829X
      url: https://sovacool.dev/
  date: today # TODO
  date-format: iso
  search: true
  repo-url: https://github.com/kelly-sovacool/phd-diss
  site-url: http://sovacool.dev/phd-diss/
  twitter-card: true
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - optifit.qmd
    - data-science.qmd
    - cdiff.qmd
    - discussion.qmd
    - references.qmd

bibliography: references.bib 
fontsize: 12pt

format:
  html:
    theme: cosmo
    title-block-banner: true
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header: preamble.tex
