# Predicting _C. difficile_ infection severity from the taxonomic composition of the gut microbiome

```{r}
# this is a dummy code block to force inline code chunks to render correctly
```

## Preamble

This chapter aims to predict CDI severity from the taxonomic composition of the gut
microbiome.
We trained models on OTU relative abundances to predict four different severity
definitions,
identified features of the microbiota that may prevent or promote severity,
and assessed the potential clinical value of micriobiome-based
prediction models.

I performed all of the analysis and created the figures and tables for this chapter.
Other co-authors conceived of the study, processed samples, and assisted in
training ML models.
This chapter will be submitted to a peer-reviewed journal with the following
co-authors:
Kelly L. Sovacool, Sarah E. Tomkovich, Megan L. Coden, Jenna Wiens,
Vincent B. Young, Krishna Rao, and Patrick D. Schloss.

### another abstract?

Prior studies to date have trained models to predict severe CDI outcomes using
routine clinical data, selected serum biomarkers, curated variables from EHR
data, or entire EHRs.
The ultimate goal is to build models that can be used to predict soon after
diagnosis which patients are at risk of experiencing disease-related
complications so that clinicians can tailor treatments to prevent severe
outcomes.
While age and immunocompetence are important factors in CDI severity, the role
of the gut microbiome has been under-explored.
In mouse studies, the gut microbiota prior to _C. difficile_ exposure
have been associated with differences in _C. difficile_ colonization, infection,
clearance, and moribundity.
As a result, we hypothesized that the initial state of the microbiome could be
used to predict severe CDI outcomes in humans.
We profiled the taxonomic composition of the bacterial microbiota from stool
samples collected on the day of diagnosis from 1,277 CDI patients, then
trained ML models to predict CDI severity using four different severity
definitions.
We found that using as much data as possible for model training while using
physicians' determinations of CDI-attributable severity when available were
paramount for good model performance, as the severity outcomes were highly
imbalanced.
_Enterococcus_ was the most important OTU contributing to model performance and
was associated with severity, which concords well with the literature.
Our model performed as well as a prior EHR-based model extracted on the day of
diagnosis, but not as well as an EHR-based model extracted two days after
diagnosis.
A preliminary analysis of the potential clinical value of severity prediction
models showed modest performance at the 95th percentile of risk, but further
work is needed to determine whether deploying OTU-based models would mark an
improvement over current clinical practices.

<!--
we do not know which antibiotics were prescribed to treat these CDI cases, nor
which antibiotics patients may have taken prior to the CDI.
differences in microbiota between patients may be due to different abx...
different antibiotics have been shown to create different forms of dysbiotic
microbiota [@berkell_microbiota-based_2021] and
differential cdi clearance [@tomkovich_initial_2020].


Models to guide treatment options. In the case of low-risk and non-invasive treatments
such as choosing between oral antibiotics, a higher number of false positives may
be tolerable as long as treatment cost is not unbearably high. However, for highly
invasive and irreversibly treatments such as colectomy, false positives must be minimized.

bezlotoxumab shown to prevent systemic organ damage in a mouse study [@mileto_bezlotoxumab_2022].
-->
