name: Render and Publish Quarto Project
on:
  push:
    paths:
      - _quarto.yml
      - *.qmd
      - *.tex

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Render with snakemake
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "render_pdf --cores 1 --use-conda --conda-frontend mamba --show-failed-logs"

    - name: Publish
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
        render: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
