name: Render and Publish Quarto Project
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/quarto-publish.yml
      - _quarto.yml
      - "*.qmd"
      - "*.tex"
      - "_freeze/**"

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2
    - uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true
    # - name: Render with snakemake
    #   uses: snakemake/snakemake-github-action@v1.24.0
    #   with:
    #     directory: .
    #     snakefile: workflow/Snakefile
    #     args: "render_pdf --cores 1 --use-conda --conda-frontend mamba --show-failed-logs"
    - name: Publish
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
        #render: false
